### ISSUE TITLE
Migrate State links from front page

### ISSUE THREAD

**Issue by gjwgit** [anusii/crisper-website#29]
On the home page, on  the left hand side we have the Resources and State links. People are clicking there thinking they are going into CRISPER ACT for example. Suggestion is to add a 5th picture box on the right for Government Resources and add an attractive page with these links (perhaps state logos).

**Comment by gjwgit** [comment]
I removed the list from the front page for now and added into the footer. Perhaps that is okay. @septianrazi to check layout in footer has not been disturbed to much!

**Comment by septianrazi** [comment]
I have added the new card on index.html and made the government_resources.html to direct to. Currently it is only simple buttons with text as seen below:

![image](https://user-images.githubusercontent.com/28195428/133552838-9c58d6ac-45e1-4831-aef6-5b462338e821.png)

**Comment by septianrazi** [comment]
I have also created another branch with the government logos attached too, however we may need some approval from these departments before we are allowed to use their logo's on our website:

**Comment by septianrazi** [comment]
To do:

Chnage the logos to website thumbnails
